### ISSUE TITLE
Nomad Job driver for Exec

### ISSUE THREAD

**Issue by RupertBothma** [star3am/hashiqube#34]
In the Nomad.sh setup:
it is set to enable raw_exec 

`plugin "raw_exec" {
  config {
    enabled = true
  }
}`

But if you try run a job with nomad it is saying missing drivers error. 
* Constraint "missing drivers": 1 nodes excluded by filter
![Screenshot 2024-05-14 at 13 58 15](https://github.com/star3am/hashiqube/assets/41477249/208787a5-a5a9-4056-a95b-7d3ad0140074)

example: 

```
Job
  group
    task {
      driver = "raw_exec"
     }
```
Is there some other config required ?

**Comment by RupertBothma** [comment]
sorry forgot to mention my versions:
Vagrant 2.4.1
Docker for Desktop on Mac: 4.24.2
Nomad 1.7.7

**Comment by star3am** [comment]
Hi @RupertBothma  - I have added an example Nomad job for using Exec driver. Have a look here and let me know if that helps.  https://github.com/star3am/hashiqube/blob/master/nomad/nomad/jobs/exec.nomad
